server:
  port: 8082

spring:
  application:
    name: servico-entrega
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
